/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cloud_logic_custom": [
        {
            "name": "qrv1API",
            "endpoint": "https://a05rzy45k0.execute-api.ca-central-1.amazonaws.com/deploy",
            "region": "ca-central-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "ca-central-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "customers-deploy",
            "region": "ca-central-1"
        },
        {
            "tableName": "sysVars-deploy",
            "region": "ca-central-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ca-central-1:fa2da488-3f3d-40b9-9e6b-eec9a9f5a794",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_nw8mLuXyy",
    "aws_user_pools_web_client_id": "2d9mj328jtlql4tal8cst6db8c",
    "oauth": {}
};


export default awsmobile;
